import { fileURLToPath } from "node:url";
import path from "node:path";

/**
 * The benchmark's stored shape, and the Markdown table generated from it.
 *
 * The table in bench/RESULTS.md is produced by this file from
 * bench/results.json. Nothing is transcribed: if a cell has no number it is
 * because the run that would have produced it did not succeed, and the table
 * says so.
 */

const here = path.dirname(fileURLToPath(import.meta.url));

export const RESULTS_PATH = path.join(here, "results.json");

export interface SurgicalRow {
  tokens: number;
  elapsedMs: number;
  jobId: string;
  changesProposed: number;
  changesInScope: number;
  changesOutOfScope: number;
}

export interface WholeDocumentRow {
  tokens: number;
  elapsedMs: number;
  jobId: string;
}

export interface BenchmarkRow {
  pages: number;
  words: number;
  documentTextTokens: number;
  selectionTextTokens: number;
  surgical: SurgicalRow | null;
  wholeDocument: WholeDocumentRow | null;
  /** What shared/tokens.ts would have predicted, for calibration. */
  estimatedWholeDocument: number | null;
  measuredAt: string;
  surgicalError?: string;
  wholeDocumentError?: string;
}

export interface BenchmarkFile {
  generatedAt: string;
  modelTier: string;
  wordsPerPage: number;
  instruction: string;
  rows: BenchmarkRow[];
}

function n(value: number | null | undefined): string {
  return value === null || value === undefined ? "—" : value.toLocaleString("en-US");
}

function pct(value: number | null): string {
  return value === null ? "—" : `${(value * 100).toFixed(2)}%`;
}

export function renderReport(file: BenchmarkFile): string {
  const lines: string[] = [];

  lines.push("# TokenScope benchmark results");
  lines.push("");
  lines.push("Generated by `npm run bench`. Do not edit by hand.");
  lines.push("");
  lines.push(`- Run at: ${file.generatedAt}`);
  lines.push(`- Model tier: \`${file.modelTier}\``);
  lines.push(`- Page size: ${file.wordsPerPage} words`);
  lines.push(`- Instruction: "${file.instruction}"`);
  lines.push("");
  lines.push(
    "**Surgical** and **Whole document** are both measured: each is the " +
      "`metadata.cumulative_tokens` SuperDocs reported for a real job it ran on that " +
      "document. **Selection** and **Document** are text-token counts of the actual " +
      "strings, tokenized locally."
  );
  lines.push("");
  lines.push(
    "| Document | Words | Selection tokens | Document tokens | Surgical tokens | Whole-document tokens | Savings |"
  );
  lines.push("| --- | ---: | ---: | ---: | ---: | ---: | ---: |");

  for (const row of file.rows) {
    const surgical = row.surgical?.tokens ?? null;
    const whole = row.wholeDocument?.tokens ?? null;
    const ratio =
      surgical !== null && whole !== null && whole !== 0 ? (whole - surgical) / whole : null;

    lines.push(
      `| ${row.pages} pages | ${n(row.words)} | ${n(row.selectionTextTokens)} | ` +
        `${n(row.documentTextTokens)} | ${n(surgical)} | ${n(whole)} | ${pct(ratio)} |`
    );
  }

  lines.push("");
  lines.push("## Estimator calibration");
  lines.push("");
  lines.push(
    "The task pane shows an *estimated* whole-document cost until a real one is " +
      "measured. This table is how far that estimate was from the measured value on " +
      "this run."
  );
  lines.push("");
  lines.push("| Document | Estimated | Measured | Estimate ÷ measured |");
  lines.push("| --- | ---: | ---: | ---: |");

  for (const row of file.rows) {
    const estimate = row.estimatedWholeDocument;
    const measured = row.wholeDocument?.tokens ?? null;
    const ratio =
      estimate !== null && measured !== null && measured !== 0
        ? `${(estimate / measured).toFixed(2)}×`
        : "—";

    lines.push(`| ${row.pages} pages | ${n(estimate)} | ${n(measured)} | ${ratio} |`);
  }

  lines.push("");
  lines.push("## Scope check");
  lines.push("");
  lines.push(
    "Every surgical run is checked: how many changes SuperDocs proposed, and how many " +
      "of them fell inside the selected paragraph. A run that edits anything else is a " +
      "failed run, whatever it cost."
  );
  lines.push("");
  lines.push(
    "| Document | Changes proposed | In scope | Out of scope | Surgical wall time | Whole-document wall time |"
  );
  lines.push("| --- | ---: | ---: | ---: | ---: | ---: |");

  for (const row of file.rows) {
    const s = row.surgical;
    const w = row.wholeDocument;

    lines.push(
      `| ${row.pages} pages | ${n(s?.changesProposed)} | ${n(s?.changesInScope)} | ` +
        `${n(s?.changesOutOfScope)} | ` +
        `${s ? `${(s.elapsedMs / 1000).toFixed(1)}s` : "—"} | ` +
        `${w ? `${(w.elapsedMs / 1000).toFixed(1)}s` : "—"} |`
    );
  }

  const failures = file.rows.filter(
    (r) => r.surgicalError !== undefined || r.wholeDocumentError !== undefined
  );

  if (failures.length > 0) {
    lines.push("");
    lines.push("## Runs that did not complete");
    lines.push("");

    for (const row of failures) {
      if (row.surgicalError !== undefined) {
        lines.push(`- **${row.pages} pages, surgical**: ${row.surgicalError}`);
      }

      if (row.wholeDocumentError !== undefined) {
        lines.push(`- **${row.pages} pages, whole-document**: ${row.wholeDocumentError}`);
      }
    }
  }

  lines.push("");
  lines.push("### Job ids");
  lines.push("");
  lines.push("| Document | Surgical job | Whole-document job |");
  lines.push("| --- | --- | --- |");

  for (const row of file.rows) {
    lines.push(
      `| ${row.pages} pages | \`${row.surgical?.jobId ?? "—"}\` | ` +
        `\`${row.wholeDocument?.jobId ?? "—"}\` |`
    );
  }

  lines.push("");

  return lines.join("\n");
}
